
export const mockData = [
  {
    objectid: '123',
    applicant: "Bob's Donut Truck",
    facilitytype: 'Truck',
    address: '123 SAN FRANCISCO ST',
    status: 'APPROVED',
    permit: '12345',
    fooditems: 'Tacos: Burritos',
  },
  {
    objectid: '234',
    applicant: "Tina's Taco Truck",
    facilitytype: 'Push Cart',
    address: '123 POLK ST',
    status: 'EXPIRED',
    permit: '223344',
    fooditems: 'Tacos: Nachos',
  },
  {
    objectid: '345',
    applicant: "Adam's Breakfast Shack",
    facilitytype: 'Push Cart',
    address: '123 POLK ST',
    status: 'RECEIVED',
    permit: '67890',
    fooditems: 'Coffee: Bagels: Donuts',
  },
  {
    objectid: '567',
    applicant: "Sam's Breakfast Truck",
    facilitytype: 'Push Cart',
    address: '123 JACKSON ST',
    status: 'RECEIVED',
    permit: '67890',
    fooditems: 'Coffee: Bagels: Donuts',
  },
  {
    objectid: '789',
    applicant: "Wrap it up truck",
    facilitytype: 'Push Cart',
    address: '123 PACIFIC ST',
    status: 'RECEIVED',
    permit: '67890',
    fooditems: 'Coffee: Bagels: Donuts: Wraps',
  },
  {
    objectid: '890',
    applicant: "Shake Shack Truck",
    facilitytype: 'Truck',
    address: '123 VALLEJO ST',
    status: 'RECEIVED',
    permit: '67890',
    fooditems: 'Burgers: Fries: Hot Dogs',
  },
  {
    objectid: '112233',
    applicant: "Amy's Breakfast Shack",
    facilitytype: 'Truck',
    address: '123 LEAVENWORTH ST',
    status: 'RECEIVED',
    permit: '67890',
    fooditems: 'Coffee: Bagels: Donuts',
  },
  {
    objectid: '223344',
    applicant: "The Rolling Breakfast Cart",
    facilitytype: 'Push Cart',
    address: '123 LOMBARD ST',
    status: 'RECEIVED',
    permit: '67890',
    fooditems: 'Coffee: Bagels: Donuts',
  },
  {
    objectid: '445566',
    applicant: "Banh Mi Express",
    facilitytype: 'Push Cart',
    address: '123 CLAY ST',
    status: 'APPROVED',
    permit: '67890',
    fooditems: 'Banh Mi: Pho',
  },
  {
    objectid: '556677',
    applicant: "Burger Bus SF",
    facilitytype: 'Push Cart',
    address: '123 WASHINGTON ST',
    status: 'EXPIRED',
    permit: '12345',
    fooditems: 'Burger: Fries',
  },
  {
    objectid: '889900',
    applicant: "Pho Real Noodles",
    facilitytype: 'Push Cart',
    address: '555 POLK ST',
    status: 'RECEIVED',
    permit: '67890',
    fooditems: 'Noodles: Rice',
  },
];